### ISSUE TITLE
Support for CI

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-helpers-js#4]
Create Jenkinsfile and tell and update CI server to use it.

**Comment by DanielRodera** [comment]
I have created the pipeline in Jenkins and updated the Jenkinsfile,

Only remains to create the hook for the repository. I don't have user rights to access the settings, could you please create it?

Thanks!

**Comment by p-a-s-c-a-l** [comment]
Update Hook URI when https://github.com/clarity-h2020/simple-table-component/issues/3#issuecomment-541049553 has been resolved.

**Comment by p-a-s-c-a-l** [comment]
done
